module.exports = {
    JWT_SECRET: "licenta2019",
    BASE_URL: "http://localhost",
    STUDENT_BASE_URL: "http://flow-student",
    MAILING_BASE_URL: "http://flow-mailing",
    GATEWAY_MODULE_PORT: 8000,
    STUDENT_MODULE_PORT: 8001,
    MAILING_MODULE_PORT: 8002,
    ENROLLMENT_MODULE_PORT: 8003,
    VOLUNTEER_MODULE_PORT: 8004,
    PAYMENT_MODULE_PORT: 8005,
    ADMIN_MODULE_PORT: 8006,
    SCREENING_MODULE_PORT: 8007 
}